# Docker Compose for Production Environment
# This version includes production-optimized settings

version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: eggledger-postgres-prod
    environment:
      POSTGRES_DB: eggledgerDB
      POSTGRES_USER: eggledger
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-eggledger123}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - eggledger-prod-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eggledger -d eggledgerDB"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # EggLedger API (Production)
  api:
    build:
      context: .
      dockerfile: EggLedger.API/Dockerfile
    container_name: eggledger-api-prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=eggledgerDB;Username=eggledger;Password=${POSTGRES_PASSWORD:-eggledger123};Port=5432
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - eggledger-prod-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # EggLedger Client (Production)
  client:
    build:
      context: ./EggLedger.Client
      dockerfile: Dockerfile
      target: production
    container_name: eggledger-client-prod
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - api
    networks:
      - eggledger-prod-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

volumes:
  postgres_data_prod:

networks:
  eggledger-prod-network:
    driver: bridge
