using EggLedger.Models.Models;
using Microsoft.EntityFrameworkCore;

namespace EggLedger.Data
{
    public class ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : DbContext(options)
    {
        public DbSet<Container> Containers { get; set; } = null!;
        public DbSet<Order> Orders { get; set; } = null!;
        public DbSet<OrderDetail> OrderDetails { get; set; } = null!;
        public DbSet<RefreshToken> RefreshTokens { get; set; } = null!;
        public DbSet<Room> Rooms { get; set; } = null!;
        public DbSet<Transaction> Transactions { get; set; } = null!;
        public DbSet<User> Users { get; set; } = null!;
        public DbSet<UserRoom> UserRooms { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // Configure the Container entity
            modelBuilder.Entity<Container>(entity =>
            {
                // Primary Key configuration
                entity.HasKey(e => e.ContainerId);
                // Ensure Guid primary keys are generated by the database when added
                entity.Property(e => e.ContainerId).ValueGeneratedOnAdd();

                // Property configurations
                entity.Property(e => e.ContainerName)
                      .IsRequired()
                      .HasMaxLength(255); // Set maximum length for string property
                entity.Property(e => e.PurchaseDateTime).IsRequired();
                entity.Property(e => e.TotalQuantity).IsRequired();
                entity.Property(e => e.RemainingQuantity).IsRequired();
                entity.Property(e => e.Amount)
                      .IsRequired()
                      .HasColumnType("decimal(18,2)"); // Define precision for decimal type

                // Relationships (Foreign Keys)
                // Container to User (Buyer)
                entity.HasOne(d => d.Buyer)
                      .WithMany(p => p.Containers) // User has many Containers (as a buyer)
                      .HasForeignKey(d => d.BuyerId)
                      .OnDelete(DeleteBehavior.Restrict); // Prevent deleting a User if they have associated Containers

                // Container to Room
                entity.HasOne(d => d.Room)
                      .WithMany(p => p.Containers) // Room has many Containers
                      .HasForeignKey(d => d.RoomId)
                      .OnDelete(DeleteBehavior.Cascade); // Deleting a Room will delete its associated Containers
            });

            // Configure the Order entity
            modelBuilder.Entity<Order>(entity =>
            {
                // Primary Key configuration
                entity.HasKey(e => e.OrderId);
                entity.Property(e => e.OrderId).ValueGeneratedOnAdd();

                // Property configurations
                entity.Property(e => e.OrderName)
                      .IsRequired()
                      .HasMaxLength(255);
                entity.Property(e => e.Datestamp).IsRequired();
                entity.Property(e => e.Quantity).IsRequired();
                entity.Property(e => e.Amount)
                      .IsRequired()
                      .HasColumnType("decimal(18,2)");
                // Assuming OrderType and OrderStatus are enums, EF Core maps them to integer columns by default
                entity.Property(e => e.OrderType).IsRequired();
                entity.Property(e => e.OrderStatus).IsRequired();

                // Relationships (Foreign Keys)
                // Order to User
                entity.HasOne(d => d.User)
                      .WithMany(p => p.Orders) // User has many Orders
                      .HasForeignKey(d => d.UserId)
                      .OnDelete(DeleteBehavior.Restrict); // Prevent deleting a User if they have associated Orders
            });

            // Configure the OrderDetail entity
            modelBuilder.Entity<OrderDetail>(entity =>
            {
                // Primary Key configuration
                entity.HasKey(e => e.OrderDetailId);
                entity.Property(e => e.OrderDetailId).ValueGeneratedOnAdd();

                // Property configurations
                entity.Property(e => e.DetailQuantity).IsRequired();
                entity.Property(e => e.Price)
                      .IsRequired()
                      .HasColumnType("decimal(18,2)");
                entity.Property(e => e.Amount)
                      .IsRequired()
                      .HasColumnType("decimal(18,2)");
                entity.Property(e => e.OrderDetailStatus).IsRequired();

                // Relationships (Foreign Keys)
                // OrderDetail to Order
                entity.HasOne(d => d.Order)
                      .WithMany(p => p.OrderDetails) // Order has many OrderDetails
                      .HasForeignKey(d => d.OrderId)
                      .OnDelete(DeleteBehavior.Cascade); // Deleting an Order will delete its associated OrderDetails

                // OrderDetail to Container
                entity.HasOne(d => d.Container)
                      .WithMany(p => p.OrderDetails) // Container has many OrderDetails
                      .HasForeignKey(d => d.ContainerId)
                      .OnDelete(DeleteBehavior.Restrict); // Prevent deleting a Container if it's part of an OrderDetail
            });

            // Configure the RefreshToken entity
            modelBuilder.Entity<RefreshToken>(entity =>
            {
                // Primary Key configuration
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();

                // Property configurations
                entity.Property(e => e.Token)
                      .IsRequired()
                      .HasMaxLength(500); // Sufficient length for JWT or similar tokens
                entity.Property(e => e.Expires).IsRequired();
                entity.Property(e => e.Created).IsRequired();
                entity.Property(e => e.CreatedByIp)
                      .HasMaxLength(45); // Max length for IPv6 address
                entity.Property(e => e.Revoked).IsRequired(false); // Nullable property
                entity.Property(e => e.RevokedByIp)
                      .HasMaxLength(45);
                entity.Property(e => e.ReplacedByToken)
                      .HasMaxLength(500);

                // Relationships (Foreign Keys)
                // RefreshToken to User
                entity.HasOne(d => d.User)
                      .WithMany(p => p.RefreshTokens) // User has many RefreshTokens
                      .HasForeignKey(d => d.UserId)
                      .OnDelete(DeleteBehavior.Cascade); // Deleting a User will delete their RefreshTokens
            });

            // Configure the Room entity
            modelBuilder.Entity<Room>(entity =>
            {
                // Primary Key configuration
                entity.HasKey(e => e.RoomId);
                entity.Property(e => e.RoomId).ValueGeneratedOnAdd();

                // Property configurations
                entity.Property(e => e.RoomName)
                      .IsRequired()
                      .HasMaxLength(255);
                entity.Property(e => e.RoomCode).IsRequired();
                // Add a unique index to RoomCode to ensure uniqueness
                entity.HasIndex(e => e.RoomCode).IsUnique();
                entity.Property(e => e.IsPublic).IsRequired();
                entity.Property(e => e.CreatedAt).IsRequired();
            });

            // Configure the Transaction entity
            modelBuilder.Entity<Transaction>(entity =>
            {
                // Primary Key configuration
                entity.HasKey(e => e.TransactionId);
                entity.Property(e => e.TransactionId).ValueGeneratedOnAdd();

                // Property configurations
                entity.Property(e => e.Datestamp).IsRequired();
                entity.Property(e => e.Amount).IsRequired(); // Assuming Amount is integer as per your model
                entity.Property(e => e.Status).IsRequired(); // Assuming Status is an integer or enum

                // Relationships (Foreign Keys)
                // Transaction to Order
                entity.HasOne<Order>()
                      .WithMany(o => o.Transactions) // Order has many Transactions
                      .HasForeignKey(t => t.OrderId)
                      .OnDelete(DeleteBehavior.Cascade); // Deleting an Order will delete its associated Transactions

                // Transaction to User (Payer)
                // This requires a separate configuration as there are two foreign keys to User
                entity.HasOne<User>()
                      .WithMany(u => u.Transactions) // Assuming User has a general Transactions collection for both payer and receiver
                      .HasForeignKey(t => t.PayerId)
                      .OnDelete(DeleteBehavior.Restrict) // Prevent deleting a User if they are a Payer in a Transaction
                      .HasConstraintName("FK_Transaction_Payer"); // Custom constraint name for clarity

                // Transaction to User (Receiver)
                entity.HasOne<User>()
                      .WithMany() // Assuming no specific navigation collection on User for 'received' transactions, or it's implicitly handled by the general 'Transactions' collection.
                      .HasForeignKey(t => t.ReceiverId)
                      .OnDelete(DeleteBehavior.Restrict) // Prevent deleting a User if they are a Receiver in a Transaction
                      .HasConstraintName("FK_Transaction_Receiver"); // Custom constraint name for clarity
            });

            // Configure the User entity
            modelBuilder.Entity<User>(entity =>
            {
                // Primary Key configuration
                entity.HasKey(e => e.UserId);
                entity.Property(e => e.UserId).ValueGeneratedOnAdd();

                // Property configurations
                entity.Property(e => e.FirstName)
                      .IsRequired()
                      .HasMaxLength(100);
                entity.Property(e => e.LastName)
                      .HasMaxLength(100);
                entity.Property(e => e.Email)
                      .IsRequired()
                      .HasMaxLength(255);
                // Add a unique index to Email to ensure uniqueness
                entity.HasIndex(e => e.Email).IsUnique();
                entity.Property(e => e.PasswordHash)
                      .HasMaxLength(500); // Sufficient length for hashed passwords
                entity.Property(e => e.Role).IsRequired(); // Assuming Role is an integer or enum
                entity.Property(e => e.Provider)
                      .HasMaxLength(50); // For external login providers (e.g., "Google", "Facebook")
            });

            // Configure the UserRoom entity (Join table for Many-to-Many between User and Room)
            modelBuilder.Entity<UserRoom>(entity =>
            {
                // Primary Key configuration
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();

                // Property configurations
                entity.Property(e => e.IsAdmin).IsRequired();
                entity.Property(e => e.JoinedAt).IsRequired();

                // Composite unique index to ensure a User can only be associated with a Room once
                entity.HasIndex(ur => new { ur.UserId, ur.RoomId }).IsUnique();

                // Relationships (Foreign Keys)
                // UserRoom to User
                entity.HasOne(d => d.User)
                      .WithMany(p => p.UserRooms) // User has many UserRoom entries
                      .HasForeignKey(d => d.UserId)
                      .OnDelete(DeleteBehavior.Cascade); // Deleting a User will delete their UserRoom associations

                // UserRoom to Room
                entity.HasOne(d => d.Room)
                      .WithMany(p => p.UserRooms) // Room has many UserRoom entries
                      .HasForeignKey(d => d.RoomId)
                      .OnDelete(DeleteBehavior.Cascade); // Deleting a Room will delete its UserRoom associations
            });
        }
    }
}