<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DTOs\**" />
    <EmbeddedResource Remove="DTOs\**" />
    <None Remove="DTOs\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EggLedger.Models\EggLedger.Models.csproj" />
  </ItemGroup>

</Project>
