@EggLedger.API_HostAddress = https://localhost:7224
@token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImFhOGUxZmJmLTUyZTItNGU4My1iYTZkLWMxZDQ5YTEwMDFkZCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImpvaG5AZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiIxIiwiZXhwIjoxNzUwNzkxNDY0LCJpc3MiOiJFZ2dMZWRnZXJBUEkiLCJhdWQiOiJFZ2dMZWRnZXJBcHAifQ.MWFB6MZK2M6_a_qPqIx_P5uusw70CmRso4lb-LEHjgo"

GET {{EggLedger.API_HostAddress}}/api/user

###

POST {{EggLedger.API_HostAddress}}/api/user
Content-Type: application/json

{
  //UserCreateDto
}

###

GET {{EggLedger.API_HostAddress}}/api/user/profile
Authorization: Bearer {{token}}
###

DELETE {{EggLedger.API_HostAddress}}/api/user/{id}

###

GET {{EggLedger.API_HostAddress}}/api/user/{id}

###

PUT {{EggLedger.API_HostAddress}}/api/user/{id}
Content-Type: application/json

{
  //UserUpdateDto
}

###

@name login
POST {{EggLedger.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "securePassword123"
}

###
